spring:
  config:
    activate:
      on-profile: dev
auth:
  jwt:
    access-exp: 86400
    secret-key: rReAe9YgI0bQI8aBRf2J4AlnNRT8HxflEB8JMA4m0Uw
    refresh-exp: 7776000
    refresh-secret-key: 1bQI8aBRf2J4AlnNRT8HxflEB8JMA4m0UwrReAe9YgI0
oauth:
  naver:
    client-id: uwVVXENpY4f1Oo7ZBIez
    client-secret: om_FdkKuWR
    redirect-uri: "http://localhost:3000/auth/callback/naver"
  kakao:
    client-id: ef261c51ab37b450c0686433674d30f1
    client-secret: dngJPLHZ7WjNC4xz5LIOCeDKDZkn5SWQ
    redirect-uri: "http://localhost:3000/auth/callback/kakao"
---
spring:
  config:
    activate:
      on-profile: prod
auth:
  jwt:
    access-exp: 86400
    secret-key: rReAe9YgI0bQI8aBRf2J4AlnNRT8HxflEB8JMA4m0Uw
    refresh-exp: 7776000
    refresh-secret-key: 1bQI8aBRf2J4AlnNRT8HxflEB8JMA4m0UwrReAe9YgI0
oauth:
  naver:
    client-id: uwVVXENpY4f1Oo7ZBIez
    client-secret: om_FdkKuWR
    redirect-uri: "http://localhost:3000/auth/callback/naver"
  kakao:
    client-id: ef261c51ab37b450c0686433674d30f1
    client-secret: dngJPLHZ7WjNC4xz5LIOCeDKDZkn5SWQ
    redirect-uri: "http://localhost:3000/auth/callback/kakao"